name: Build and Upload Flutter Release APK

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      # Step 3: Set up Flutter
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.21.0' # Uses Dart 3.0.0
          channel: 'stable'

      # Step 4: Cache Flutter dependencies
      - name: Cache Flutter dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.pub-cache
          key: ${{ runner.os }}-flutter-${{ hashFiles('**/pubspec.lock') }}
          restore-keys: |
            ${{ runner.os }}-flutter-



      # Step 6: Install dependencies
      - name: Install dependencies
        run: flutter pub get

      # Step 7: Decode and store signing key
      - name: Decode Keystore
        env:
          SIGNING_KEY_BASE64: ${{ secrets.SIGNING_KEY_BASE64 }}
        run: |
          echo $SIGNING_KEY_BASE64 | base64 -d > android/app/keystore.jks

      # Step 8: Configure signing
      - name: Configure signing
        run: |
          cat > android/app/key.properties <<EOF
          storeFile=keystore.jks
          storePassword=${{ secrets.KEYSTORE_PASSWORD }}
          keyAlias=${{ secrets.KEY_ALIAS }}
          keyPassword=${{ secrets.KEY_PASSWORD }}
          EOF

      # Step 9: Build release APK
      - name: Build Release APK
        run: flutter build apk --release --target-platform android-arm
        # android-arm ensures compatibility with Android 4.4 devices

      # Step 10: Upload release APK
      - name: Upload Release APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release-apk
          path: build/app/outputs/flutter-apk/app-release.apk
